// Mortgage Form
export const SET_MORTGAGE_INITIAL_DATA = 'SET_MORTGAGE_INITIAL_DATA';
export const ADD_USER_TO_MORTGAGE_PROPOSAL = 'ADD_USER_TO_MORTGAGE_PROPOSAL';
export const ADD_MORTGAGE_PROPOSAL = 'ADD_MORTGAGE_PROPOSAL';
